using UnityEngine;

public class ControlCube : MonoBehaviour
{
    float speed = 0.002f;
    float steer = 0.03f;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKey(KeyCode.W))
        {
            transform.position += transform.forward * speed;
        }
        if (Input.GetKey(KeyCode.S))
        {
            transform.position -= transform.forward * speed;
        }
        if (Input.GetKey(KeyCode.A)){
            transform.Rotate(0f, -steer, 0f, Space.Self);
        }
        if (Input.GetKey(KeyCode.D)){
            transform.Rotate(0f, steer, 0f, Space.Self);
        }
    }
}
